# @see https://dev.to/smitjel/kicking-the-tires-on-github-actions-45g9
# @see https://boringrails.com/articles/building-a-rails-ci-pipeline-with-github-actions/

name: Test

on: 
  pull_request:
    types:
      - opened
      - reopened
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Setup gems
      run: |
        gem install bundler
        bundle config set --local deployment 'true'
        bundle config set --local with 'test'
        bundle install --jobs 4 --retry 3
    - name: Linter
      run: |
        bundle exec rubocop --display-cop-names
    - name: RSpec
      run: |
        bundle exec rspec ./spec
